### ISSUE TITLE
Person-detection sensor takes a long time to reset

### ISSUE THREAD

**Issue by Schnabulation** [JimStar/reolink_cctv#13]
**Describe the bug**
My camera (E1 Outdoor) has an A.I. person and car detection. Using the Reolink-app on my phone or computer the detection works perfectly fine: it detects objects and once the object leaves the frame it resets.

In Home Assistant however the person detection sensor takes a very long time to revert to "idle". Sometimes it reverts fine and sometimes it takes up to a couple of hours to revert back.

**To Reproduce**
Trigger the person detection by stepping in front of the camera. Check the sensor in Home Assistant. It does not revert back to "idle" but stays in state "detected".

**Expected behavior**
The sensor should revert back to "idle" once the object leaves the frame.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/1053834/194562765-ddea5844-ed5f-4b8b-848c-fd6a651a8253.png)

**Environment:**
 - Home Assistant 2022.10.0
 - Supervisor 2022.09.1
 - Operating System 9.0
 - Frontend 20221005.0 - latest 
 - Reolink NVR/camera model: 3x Reolink E1 Outdoor (no NVR, directly connected)
 - NVR/camera firmware: v3.1.0.804

**Additional context**
I did not have this issue with the "old" Reolink integration.

**Comment by JimStar** [comment]
Could you please switch on debug logging, and post here a full log-file, from HA restart, and covering the time when detection triggered but did not went back to "clear"...  
Logging config:  
```
logger:
  default: warning
  logs:
    custom_components.reolink_cctv: debug
    reolink_ip: debug
```

**Comment by Schnabulation** [comment]
Please excuse my late reply - I was away over the weekend.

I have noticed that it's not only Home Assistant that does not show the cameras as "clear" but also my Synology (which records the stream). So I think the issue is with the Reolink cameras and not your integration. I'll contact Reolink.

**Comment by JimStar** [comment]
Actually, this must already be **fixed** in this component, and should work OK.  
Just set the motion-off timeout to desired value in the integration's config...

**Comment by JimStar** [comment]
Of course this is initially the **Reolink's problem** - this camera never sends the "motion is off" ONVIF notification. But this component now workarounds this issue, and must work well with this in latest version...

**Comment by Schnabulation** [comment]
Thank you for your work! However - I also need Reolink to fix this because my Synology NVR is dependent on the ONVIF motion sensor. If the sensor does not clear my Synology keeps recording.

**Comment by JimStar** [comment]
I'm not sure about exactly what happens with this camera, because you've not posted the debug-log here.  
Either this camera just fails to send the ONVIF "motion is off" notification as I guessed above, or it just doesn't send any ONVIF notifications at all (in this case you would get the motion-events by polling only). This component will work anyways in both cases, but it would be much more efficient if there are ONVIF notifications sent by a camera - much less HA computing and network resources would be spent, the component would be just waiting for a notification from cameras, instead of polling them all the time back and forth...

**Comment by Schnabulation** [comment]
Do you still want the debug log? I can activate it if it helps.

I have also placed a ticket on Reolinks website. I suspect that you are right regarding the ONVIF "motion is off" notification. This error started to occure once I upgraded to the latest firmware (that is only available from the Reolink support directly).

**Comment by JimStar** [comment]
Any additional info helps to improve the component. So if you would attach a debug-log - it would be helpful anyway...

**Comment by Schnabulation** [comment]
[home-assistant.log](https://github.com/JimStar/reolink_cctv/files/9752053/home-assistant.log)

Restarted HA on 09:00 am, triggered the person detection of the camera "Eingang" and "Garten" at around 09:04 am. Stopped the log at around 09:10 am. I hope it helps.

**Comment by JimStar** [comment]
Thanks!  
I see in your log now, that is **not that Reolink issue** I tried to guess. It might me some issue with this component, which I could fix... Looking into it...

**Comment by Schnabulation** [comment]
Can you check f.e. line 3056:

```
"MD" : "111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111"
```

The value MD (which I suspect is "motion detected") is always at 1. It never reverts back to 0. This is the value that triggers my Synology NVR to always record. That should be an issue, no?

**Comment by JimStar** [comment]
No, that part is not what you think it is.

Long explanation, sorry:

I actually found one issue I could fix in the component, but still not sure if it would work, it depends if Reolink has no other issue I suspect could be in their firmware. I'll try to explain what is the **possible** issue, you need to check if the "not getting clear" issue persists in the version **0.0.12** I'm going to release soon, but you need to set the "motion force-off timeout" to "0" in the integration config before testing. If the issue persists in **0.0.12** after that - then you'll have what to report to Reolink. But you could still increase this new setting to say 5 seconds to workaround it by the component, before it gets fixed by Reolink.  
But if it would get back to "Clear" without problems in **0.0.12** even with this setting set to "0" - then there are no Reolink issues, and this just got fixed by the **0.0.12** version of this component.

The sequence of events is like this:  
1. The camera sees some **motion** and **person** types of motion at the same time, and sends the "I see some motion" notification (not the "rich" one I seen with other cameras, where it tells what **kind** of motions are detected right inside the notification, but the simple one - just "I see some motion").
2. The component receives the notification, and sends the command to the camera: "tell me what kinds of motions are triggered?".
3. The camera responds with "I see **generic motion**, and **person**".
4. The component switches on the **motion** and **person** sensors.
5. The camera sends the "motion stopped" notification (again, without telling what of those two kinds has stopped).
6. The component asks the camera again: "tell me what kinds of motions are triggered right now?".
7. The camera must respond "I don't see the **ANY motion** anymore", so that the component switches off all sensors. But if the camera, after sending "no motions anymore" notification, still responds to the command that it still sees some motion, then this could be some Reolink bug... Because there must be no motions of **any** kind reported anymore by camera in response to asking command after it had sent "I see no motions anymore" notification to HA...

I'm going to release the **0.0.12** soon...

**Comment by JimStar** [comment]
The **0.0.12** has just been released, and I think it should work OK for you now, even with the "motion force-off timeout" setting set to "0"... All the sensors now should come back to "Clear" as soon as they receive the notification from camera...

**Comment by JimStar** [comment]
If **0.0.12** will work OK for you - then maybe there is a bug in your Synology not stopping recording properly, not in Reolink...;)

**Comment by Schnabulation** [comment]
Updated to 0.0.12 and set "force-off timeout" back to 0. Will be testing now.

On another note: After the upgrade the aspect ratio seems to have changed. Is this supposed to be?

**Comment by JimStar** [comment]
I didn't change anything regarding aspect ratio... It's actually the camera's function what image size it provides...

**Comment by Schnabulation** [comment]
Actually no! Since the update I never had the issue again - even with "force-off timeout" set to 0. Thank you very much for your help.

Btw: I was also able to fix the Synology issue - I had to reload the ONVIF settings in Synology.
