### ISSUE TITLE
New official integration in next release?

### ISSUE THREAD

**Issue by KentuckyMC** [JimStar/reolink_cctv#141]
Hello all,

As I always read the beta release notes, I saw that Reolink gets a official integration with Home Assistant. Maybe good for everyone (as also the maker of this repository) to help the core of Home Assistant and move towards there and bundle forces! :)

Thanks a lot!

https://rc.home-assistant.io/integrations/reolink

**Comment by JimStar** [comment]
The mentioned "official" Reolink integration is just **this exact** component adopted as a pull-request in the official Home Assistant repo.

I still continue working on **this** initial branch, and there were already a couple of things improved here already **after** the HA pull-request based on this repo was made... And for now I still plan to continue working on **this** initial integration, because I see this way much more responsive in reaction to any improvements: I just can quickly fix/improve any bug-report/feature-request sometimes making a new release in just half an hour after the ticket was opened, when everybody else (including myself) can make use of a new component version **immediately**. In comparison to waiting for a Home Assistant's next official full-blown clunky release for every little bug fix in the Reolink functionality... Meh... Especially that I use Reolink cameras and NVR myself in my house, and I want to be able to be **quick** with any changes/improvements/fixes I make to the system.

I much more prefer the plugin-approach, than "everything in all-in-one overblown release"... This way plugin-developers can update *just a little part* of HA functionality when needed, *independently*, releasing a new fixed/improved version of a plugin, without updating the core HA system itself every time... Especially important when for example some Reolink firmware breaking change would be released just after a new HA release, and people who updated to this new Reolink firmware would need now to wait for the **next** HA full release that hopefully would have a fix in the Reolink functionality part... just to get their devices back working again... Meh...

**Comment by KentuckyMC** [comment]
Ah okay, I understand this approach. But at least they have an official way for the ones not using HACS for example, based on this repo. That's good at least. 

The 'patch' releases they do in HA, are those for the bugfixes you mention above?  Or are those patches not used for this? Love this repo, so will give HA core integration a try, but guess I will fallback on this one for the quick support you mentioned as well. Thanks for your effort!
