### ISSUE TITLE
Time to switch to the "official" Reolink integration?

### ISSUE THREAD

**Issue by echoztrip** [JimStar/reolink_cctv#153]
Hey JimStar, thanks heaps for all the work you have done on this. 

Wasn't sure how best to get in contact with you directly, but I noticed that you slowed down releases around the same time as HA included a Reolink integration (with contributions from yourself and others).  I guess the other plausible explanation is that you could be on holidays ;)

Either way, I wondered if this means that considering your work has gone into the HA integration, would it make sense for people using your HACS integration to make the swap?

**Comment by JimStar** [comment]
Already answered few times, for example here: [https://github.com/JimStar/reolink_cctv/discussions/151#discussioncomment-4708723](https://github.com/JimStar/reolink_cctv/discussions/151#discussioncomment-4708723)

Slowed down releases are only because there are nothing to improve so far... Works OK in my own house's CCTV system, and no tickets from anybody, and no answers to my questions in some existing feature-requests...

**Comment by echoztrip** [comment]
Fair answer mate. I've got no problems either... except for waiting on
reolink to fix the NVR motion channel 0 issue!

Sorry to hear about Jacinta today!

Cheers
