### ISSUE TITLE
No binary switches

### ISSUE THREAD

**Issue by droopycool** [JimStar/reolink_cctv#169]
I just added a new camera (Duo 2 PoE) and the binary switches are not showing up (IR Lights, Record Audio, Siren & Spotlight).

This is strange because I have 2 other cameras of the same models since months ago, and the switches appeared OK for those.

I just aplugged in the new camera to the NVR and reloaded the integration

![image](https://user-images.githubusercontent.com/87247848/218821881-7da74977-7e44-46b3-af27-d590a7ead505.png)
![image](https://user-images.githubusercontent.com/87247848/218821913-66503139-f37c-49d3-ba38-e159efb5f952.png)

Home assistant 2023.2.4
NVR RLN8-410 - v3.2.0.214_22120252
Camera Reolink Duo 2 PoE

**Comment by JimStar** [comment]
Please attach a full debug log file, with the logging-config from the issue-template.

**Comment by sergeknystautas** [comment]
Attached is the debug (without my dumb grep'ing error) from #170.

[home-assistant_2023-02-14T23-39-21.216Z.log](https://github.com/JimStar/reolink_cctv/files/10738065/home-assistant_2023-02-14T23-39-21.216Z.log)

**Comment by JimStar** [comment]
@sergeknystautas
I see for example that for two of your cameras on channel 3 and 5 (zero-based index) your NVR returns error for `GetWhiteLed` command (which should receive data for spotlight switch):  
```
 {
    "cmd" : "GetWhiteLed",
    "code" : 1,
    "error" : {
       "detail" : "send failed",
       "rspCode" : -16
    }
 }
```
Thus the switch gets not created by the component. Same for other switches. This is not this component's issue.

This is even more weird that the camera on the channel 3 is **the same** RLC-510WA as on the channel 2 (which responds with a proper `GetWhiteLed` data).  
It looks like a Reolink firmware bug either in the NVR or in these two cameras... Try to update the firmwares, and see if your debug-log would contain all the proper response-sections for the `GetWhiteLed` command for **all** the cameras after that, not just for the first three channels (instead of current `"code" : 1` sections for these channels). If still not - try to complain to Reolink support...

**Comment by sergeknystautas** [comment]
@JimStar  I double checked the firmware and hw info for the two (in case it was different editions of RLC-510WA) and the ones sending the GetWhiteLed are identical.  I'll see if there's a configuration in the NVR as another possibility, but in any event, this gives me several paths to track down.  Thanks for your help diagnosing this!
