### ISSUE TITLE
Visitor notification fails when Doorbell POE has no internet connection

### ISSUE THREAD

**Issue by Markus9955** [JimStar/reolink_cctv#187]
Thanks for the great work on this. 

I'm currently running v0.1.19  on Home Assistant 2023.5.1

I have found that the Reolink Doorbell Camera POE (Firmware: v3.0.0.1459_22102808, Hardware: DB_566128M5MP_P) tries to connect to pushx.reolink.com when the button on the camera is pressed. If I allow this connection then the Visitor notification in Home Assistant works, however, if I block this connection at the router then Visitor notifications stops working in Home Assistant

When it failed I could see the webhook was being called when the button was pressed but then there was no more debug until the webhook was called again 15 seconds later for the button release.

I then replaced "data = await request.text()" on line 510 of host.py with:
``` 
try:
  data = await request.text()
except Exception as e:
  _LOGGER.info("Webhook request exception (%s).", e)
```

This yielded the following debug:
```
2023-05-06 00:26:15.369 INFO (MainThread) [custom_components.reolink_cctv.host] Webhook called (reolink_Front_Door_webhook).
2023-05-06 00:26:15.369 INFO (MainThread) [custom_components.reolink_cctv.host] Webhook request exception (Connection lost).
2023-05-06 00:26:19.130 DEBUG (MainThread) [custom_components.reolink_cctv] Finished fetching reolink.Front Door data in 0.737 seconds (success: True)
2023-05-06 00:26:30.692 INFO (MainThread) [custom_components.reolink_cctv.host] Webhook called (reolink_Front_Door_webhook).
2023-05-06 00:26:30.692 DEBUG (MainThread) [custom_components.reolink_cctv.host.data] Webhook received payload (reolink_Front_Door_webhook):
```

I then removed the DNS and gateway from the camera and now I reliably get the Visitor notification again. I'm not sure if this is useful to others or if it would be worth updating the code to include the above exception to assist with others debug.

**Comment by JimStar** [comment]
Feel free to reopen this after attaching a full debug log file (as per issue template).

**Comment by starkillerOG** [comment]
This issue is already fixed in the build-in Reolink integration.

@JimStar have you already tried the build in version as of HA 2023.5? It actually has quite some bugs fixed and supports more entities/features than this branch.
Only the media browser for recordings is still missing, do you use that?

@JimStar thanks again for your help at the beginning and providing the bases of the built in integration.

Could you let me know if you think something is still missing in the build in integration?
If not, maybe we could focus development on the build in integration and archive this one?
It would be more clear for users.
