### ISSUE TITLE
Question about errors and warnings

### ISSUE THREAD

**Issue by garry0garry** [JimStar/reolink_cctv#22]
Thanks for the integration! This is my first time running reolink_cctv since reolink_dev.

Home Assistant 2022.10.4, Frontend 20221010.0, HACS 1.28.0, Reolink IP NVR/cameras 0.0.12

Reolink RLC-520A hw IPC_523128M5MP v3.1.0.951_22041566 - 9 pcs.
Reolink RLC-520A hw IPC_523128M5MP_V2 v3.1.0.1228_22082201 - 2 pcs.
Reolink RLC-511WA hw IPC_523128M5MP v3.1.0.956_22041509 - 1 pc.

Settings:
HTTP, rtsp
Motion sensor off delay  (seconds) - 60
Connection timeout (seconds) - 120

What do the errors mean? Do I understand correctly that this refers to the temporary unavailability of video cameras?

```
Logger: homeassistant.config_entries
Source: config_entries.py:395
First occurred: 5:39:08 PM (2 occurrences)
Last logged: 5:39:08 PM

Config entry 'cam10' for reolink_cctv integration not ready yet: Error while trying to setup Unknown: failed to connect to device.; Retrying in background
Config entry 'cam5' for reolink_cctv integration not ready yet: Error while trying to setup Unknown: failed to connect to device.; Retrying in background

```

```
This error originated from a custom integration.

Logger: reolink_ip.api
Source: custom_components/reolink_cctv/host.py:170
Integration: reolink_cctv (documentation, issues)
First occurred: 5:39:08 PM (3 occurrences)
Last logged: 5:39:17 PM

Host 192.168.50.177:80: Unknown exception "" occurred, traceback: Traceback (most recent call last): File "/usr/local/lib/python3.10/site-packages/reolink_ip/api.py", line 2095, in send raise CredentialsInvalidError() reolink_ip.exceptions.CredentialsInvalidError
Host 192.168.50.63:80: Unknown exception "" occurred, traceback: Traceback (most recent call last): File "/usr/local/lib/python3.10/site-packages/reolink_ip/api.py", line 2095, in send raise CredentialsInvalidError() reolink_ip.exceptions.CredentialsInvalidError


```

**Comment by JimStar** [comment]
Please attach the full debug-log after this happens. You can enable the debug-logging for the component as described in the issue-template...

**Comment by JimStar** [comment]
This one looks like some problem in Reolink firmware of your cameras.  
What I see happens:  
- Right after start, the component sends the "Logout" command to a camera, to reset any possible **previous** login-sessions (because Reolink has a **limit** on the max amount of them and would not allow to login if there are already previous logins active).
- Your camera responds with not-logged-in reply, which is completely OK, 'cause previously it was properly logged-out during HA reset.
- Now the component sends the "Login" command (with username and password).
- Your camera responds with a logged-in reply containing a proper token. Which shows that the session got properly logged in on this camera.
- The component sends the get-info command to the camera, using just obtained token of just logged-in session.
- Most of your cameras reply with all the requested info. BUT just few of your cameras suddenly reply with "**please login first**" reply. Which must **not happen**, because just 0.2 seconds ago this same camera replied with "**login-session accepted**" reply containing a proper access token! And this exact token was just used by the component when asking this camera to provide some info... but the camera suddenly **rejected** it and replied with "please login first".
- 8 seconds later the component tried again: it logged in on the same camera again, received another confirmation-reply with a new access-token, and tried to send a get-info command again. And the second time camera accepted this token and replied with a proper info-response. No difference in this sequence compared to the previously failed one - the only difference that **this time** the camera suddenly **accepted** its own token...

The above definitely looks like some bug in the Reolink's firmware.  
Did you try to update the firmware in your cameras to a latest one? If yes - maybe you need to report this problem to Reolink support...

**Comment by garry0garry** [comment]
My cameras have the latest firmware.
I can make a support request, but I need to attach details to do so. It seems to me that if I start writing a request in my own words, I can get confused and the support will not understand me. Do you have the opportunity to write a text for support?

**Comment by JimStar** [comment]
Just link them my description-post here...

**Comment by garry0garry** [comment]
Can you add log entries to your description?

**Comment by JimStar** [comment]
Just give them the full log.  
I don't like any useless conversations with the Reolink support: they just always spend my time by some "we are looking into this" answers, and never fix anything I ask them to...

**Comment by garry0garry** [comment]
From Reolink: "Your request was successfully submitted"

**Comment by JimStar** [comment]
Not sure if this would help, but I've tried one workaround in **0.0.13** that *could* help with this...

Just look at the log if these `CredentialsInvalidError` still appear in there. Let me know in any case - if they still appear or not.  
Because if this workaround would not fix this - then I'd better remove it in next version. It adds a 0.5 seconds timeout after logging in - in case if it is some lag in Reolink firmware - then it should be enough for it to start accepting a token. But if it doesn't help - I'd better remove this extra timeout, to not slowdown each login process by 0.5 seconds...  
Anyway, even with these errors thrown - the component finally is able to "puncture" this Reolink issue and establish a logged-in session with a camera, just after few subsequent tries...

**Comment by garry0garry** [comment]
Home Assistant 2022.10.4, HACS 1.28.2, Reolink IP NVR/cameras 0.0.13

After restarting the HA:

```
Logger: reolink_ip.api
Source: custom_components/reolink_cctv/host.py:170
Integration: Reolink IP NVR/camera (documentation, issues)
First occurred: 09:11:21 (2 occurrences)
Last logged: 09:11:21

Host 192.168.50.62:80: Unknown exception "" occurred, traceback: Traceback (most recent call last): File "/usr/local/lib/python3.10/site-packages/reolink_ip/api.py", line 2096, in send raise CredentialsInvalidError() reolink_ip.exceptions.CredentialsInvalidError
Host 192.168.50.177:80: Unknown exception "" occurred, traceback: Traceback (most recent call last): File "/usr/local/lib/python3.10/site-packages/reolink_ip/api.py", line 2096, in send raise CredentialsInvalidError() reolink_ip.exceptions.CredentialsInvalidError
```

```
Logger: homeassistant.config_entries
Source: config_entries.py:395
First occurred: 09:11:21 (2 occurrences)
Last logged: 09:11:21

Config entry 'cam3' for reolink_cctv integration not ready yet: Error while trying to setup Unknown: failed to connect to device.; Retrying in background
Config entry 'cam10' for reolink_cctv integration not ready yet: Error while trying to setup Unknown: failed to connect to device.; Retrying in background
```

**Comment by JimStar** [comment]
Thank you for testing.  
This **definitely** looks like some Reolink bug. And it appears the 0.5 seconds delay does not help - a camera just replies with "*all OK, session created, here is an access token*", but immediately rejects the very next command sent to it with this token with "*please login first*"... And 8 seconds later **this same sequence** suddenly works OK...  
Hope Reolink guys fix it finally. But it should work for you anyway, just you'll see these `CredentialsInvalidError` in a log from time to time...

**Comment by JimStar** [comment]
BTW, I've **never** seen this with my four RLC-822A cameras, even with the login-delay ZERO. My NVR always accepts a token after it confirms the login-session is created... even when the next command is sent like 0.1 seconds after receiving a token...

**Comment by garry0garry** [comment]
Just in case. Just for statistics.
Home Assistant 2022.10.4, HACS 1.28.2, Reolink IP NVR/cameras 0.0.14

Logger: homeassistant.config_entries
Source: config_entries.py:395
First occurred: 22:00:00 (4 occurrences)
Last logged: 22:00:00

```
Config entry 'cam7' for reolink_cctv integration not ready yet: Error while trying to setup Unknown: failed to connect to device.; Retrying in background
Config entry 'cam9' for reolink_cctv integration not ready yet: Error while trying to setup Unknown: failed to connect to device.; Retrying in background
Config entry 'cam11' for reolink_cctv integration not ready yet: Error while trying to setup Unknown: failed to connect to device.; Retrying in background
Config entry 'cam12' for reolink_cctv integration not ready yet: Error while trying to setup Unknown: failed to connect to device.; Retrying in background

```

```
Logger: reolink_ip.api
Source: custom_components/reolink_cctv/host.py:170
Integration: Reolink IP NVR/camera (documentation, issues)
First occurred: 22:00:00 (8 occurrences)
Last logged: 22:00:09

Host 192.168.50.72:80: Unknown exception "" occurred, traceback: Traceback (most recent call last): File "/usr/local/lib/python3.10/site-packages/reolink_ip/api.py", line 2105, in send raise CredentialsInvalidError() reolink_ip.exceptions.CredentialsInvalidError
Host 192.168.50.14:80: Unknown exception "" occurred, traceback: Traceback (most recent call last): File "/usr/local/lib/python3.10/site-packages/reolink_ip/api.py", line 2105, in send raise CredentialsInvalidError() reolink_ip.exceptions.CredentialsInvalidError
Host 192.168.50.27:80: Unknown exception "" occurred, traceback: Traceback (most recent call last): File "/usr/local/lib/python3.10/site-packages/reolink_ip/api.py", line 2105, in send raise CredentialsInvalidError() reolink_ip.exceptions.CredentialsInvalidError
Host 192.168.50.127:80: Unknown exception "" occurred, traceback: Traceback (most recent call last): File "/usr/local/lib/python3.10/site-packages/reolink_ip/api.py", line 2105, in send raise CredentialsInvalidError() reolink_ip.exceptions.CredentialsInvalidError
```

**Comment by garry0garry** [comment]
After rebooting all cameras, there will be no errors for some time.

**Comment by JimStar** [comment]
Just wait a little bit, I'll release **0.0.15** soon... testing it right now... Most likely it will not fix this, but there is a **small** chance that it could workaround this Reolink's bug.  
I'll let here know when it's ready.

**Comment by JimStar** [comment]
**0.0.15** is now released. You can try if any changes...

**Comment by garry0garry** [comment]
Home Assistant 2022.10.4, HACS 1.28.2, Reolink IP NVR/cameras 0.0.15

```
Logger: homeassistant.config_entries
Source: config_entries.py:395
First occurred: 10:14:45 (3 occurrences)
Last logged: 10:14:45

Config entry 'cam10' for reolink_cctv integration not ready yet: Error while trying to setup 192.168.50.177:80: failed to connect to device: "".; Retrying in background
Config entry 'cam5' for reolink_cctv integration not ready yet: Error while trying to setup 192.168.50.63:80: failed to connect to device: "".; Retrying in background
Config entry 'cam12' for reolink_cctv integration not ready yet: Error while trying to setup 192.168.50.127:80: failed to connect to device: "".; Retrying in background

```
```

Logger: reolink_ip.api
Source: custom_components/reolink_cctv/host.py:173
Integration: Reolink IP NVR/camera (documentation, issues)
First occurred: 10:14:45 (3 occurrences)
Last logged: 10:14:45

Host 192.168.50.177:80: login attempt failed.
Host 192.168.50.63:80: login attempt failed.
Host 192.168.50.127:80: login attempt failed.
```

**Comment by garry0garry** [comment]
But in the end, all the cameras are connected. They work.

**Comment by garry0garry** [comment]
What is `device: ""`?

**Comment by JimStar** [comment]
Nothing important.

**Comment by garry0garry** [comment]
I have tried turning email on and off on all cameras (12 pcs). Result:

```
Logger: reolink_ip.api
Source: custom_components/reolink_cctv/switch.py:182
Integration: Reolink IP NVR/camera (documentation, issues)
First occurred: 11:38:36 (12 occurrences)
Last logged: 11:40:54

Host 192.168.50.63:80: command "SetEmail" error.
Host 192.168.50.162:80: command "SetEmail" error.
Host 192.168.50.72:80: command "SetEmail" error.
Host 192.168.50.37:80: command "SetEmail" error.
Host 192.168.50.14:80: command "SetEmail" error.

```
```
Logger: frontend.js.latest.202210100
Source: components/system_log/__init__.py:227
First occurred: 11:36:43 (7 occurrences)
Last logged: 11:40:53

:0:0 ResizeObserver loop completed with undelivered notifications.


```

**Comment by JimStar** [comment]
Regarding email - it's some separate issue. Just open another ticket, and attach a debug-log there.

Regarding `:0:0 ResizeObserver` - it is Home Assistant front-end error, nothing to do with the component. It happens often for many people, for me too.

**Comment by garry0garry** [comment]
> The above definitely looks like some bug in the Reolink's firmware.

Another problem with accessing the camera, but now from the original Reolink application for Windows. Downloading multiple consecutive videos causes the camera to become unavailable. As far as I understand, the problem is in unclosed TCP sessions on the camera.
