### ISSUE TITLE
Integration not able to log in to RLN16-410 Login rspCode -5

### ISSUE THREAD

**Issue by danielszilagyi** [JimStar/reolink_cctv#53]
**Describe the bug**
Hi, thanks for your efforts on this integration! I'm trying to replace reolink_dev, removed the configured integration then removed from HACS, installed your integration via HACS. The initial integration setup screen works, I'm getting the checkboxes with the channels then I'm getting these errors in the log:
```2022-11-09 23:04:13.008 ERROR (MainThread) [custom_components.reolink_cctv.host] Error registering a webhook reolink_HazikoNVR_webhook for HazikoNVR: maybe a duplicate device-name in your setup?```
then at some point
```2022-11-09 23:18:18.965 ERROR (MainThread) [reolink_ip.api] Failed to login at host 192.168.20.20:80.
2022-11-09 23:18:18.966 ERROR (MainThread) [reolink_ip.api] Host: 192.168.20.20:80: error obtaining host-settings response.
```

I tried renaming the NVR, deleted and readded the integration several times.
When checking the traffic between HA and NVR I can see this:

```
        POST /cgi-bin/api.cgi?cmd=Login&token=null HTTP/1.1
        Host: 192.168.20.20
        User-Agent: HomeAssistant/2022.11.2 aiohttp/3.8.1 Python/3.10
        Accept: */*
        Accept-Encoding: gzip, deflate
        Content-Length: 89
        Content-Type: application/json
```
```
        HTTP/1.1 200 OK
        Date: Wed, 09 Nov 2022 22:15:54 GMT
        Content-Type: text/html
        Transfer-Encoding: chunked
        Connection: keep-alive
        X-Frame-Options: SAMEORIGIN
        X-XSS-Protection: 1; mode=block
        X-Content-Type-Options: nosniff

        86
        [
           {
              "cmd" : "Login",
              "code" : 1,
              "error" : {
                 "detail" : "Login",
                 "rspCode" : -5
              }
           }
        ]

        0
```
I am using HA over https only and have the same internal/external URL with custom internal DNS. Would that be related?
I tried setting up the NVR with http and https as well, the outcome is the same.

My setup is RLN16-410 hw. H3MB02 with firmware 2.0.0.4725. It was working well with reolink_dev besides the annoying log filling and the motion events not being reliable.

Home Assistant 2022.11.2

thanks

**Comment by JimStar** [comment]
Just to be sure: wait for at least an hour after deleting `reolink_dev`, and only then try to add this integration.  
This is because the session length in Reolink devices is one hour, and if `reolink_dev` did not logout properly - you could end up with a previous sessions stuck and not letting to login before some session time ends...

But even if after that you would get errors - please switch on the debug logging for this integration, and attach a **full** log file here (starting with the HA restart, and you trying to add the integration).  
This issue-template had a config lines needed to enable the debug logging...

**Comment by danielszilagyi** [comment]
Hi, appreciate the so fast response.
Just added the debug lines to my config, restarted, and the integration started working without any additional config change. I don't have debug logs about the failed logins but right now it is working, I'll keep the debug log on for a while. Actually I even created a new user just to check if it is a session issue but even restarted the NVR after I saw 20+ sessions in the PC client, so pretty strange why it just started working on its own.

**Comment by JimStar** [comment]
Most likely it started working because finally some previous active session expired, and freed up the way for a new session started by `reolink_cctv`.  
These NVRs have a limited amount of sessions available - if I remember correctly, something about 2 or 3. I got this situation on mine RLN8-410 too when debugged this integration. Reolink does not allow to use their Logout command with login/pass to exit previous sessions - only with a previous session's **token**. Which makes it impossible to exit the previous stuck sessions if the token from them is already not available, even though the admin's login/pass are provided in the Logout command...
