### ISSUE TITLE
Motion events bug

### ISSUE THREAD

**Issue by no-compromise** [JimStar/reolink_cctv#58]
Hi, first, thank for your piece of code. Im messing with reolink events BUG, that you mentioned in your notes. I m in situation that each of my 6 cams recording different areas, so motion detection only from first cam is a big problem for me. 
I wrote a bug report to Reolink and here is they answer:

"Please kindly note that if we want to add the cameras connected to the NVR to third party software via ONVIF, we need to add multiple channels of the cameras. We just need to change the channel number to add cameras in different channels. We can not add a whole NVR directly."

No sure what do they mean.
Is there some workaround for this? Motion event to HA is quite crucial for me.

Thank you
Andrej

**Comment by JimStar** [comment]
This answer from them is a total bullshit. Looks like they did not even look at how this component works, before telling you this nonsense.  
This component does everything correctly. Otherwise you would not even see all your cameras after adding just one NVR entity in this integration. Moreover the prase "*connected to the NVR to third party software via ONVIF*" makes no sense, because you don't "*connect*" to a software by ONVIF: this protocol is just used for **notifications** sent by a device to a webhook. And the current ONVIF SWN standard [**does not** even mention](http://docs.oasis-open.org/wsn/wsn-ws_base_notification-1.3-spec-os.pdf) any "*channel*" entity, it is just a common notification telling to a recipient that "there is a motion on a camera". And Reolink does not mention in their documentation any modifications of the SWN standard notifications that would add a "*channel*" property in there... And their NVRs do not send this notification after any motion happened on any NVR channels other than the very first one.    
Plus they already confirmed to many different customers (including me) that this is the issue in their firmware, and they are "working on it". So I don't even know who from their command has answered you this nonsense, while Reolink **already knows** that this is **the issue in their firmware**.

And no, this can not be workarounded on this component's side. The only workaround for now is to connect to cameras separately.  
I have an NVR myself, and have all cameras connected to it. I would not like to change the topography of my network just because of this bug, so I've decided to just wait and see if they are really going to release a fixed NVR firmware (as they promised) or not... If no release in one/two months - then I'm probably going to change the topology and connect to cameras separately.

**Comment by JimStar** [comment]
I think I'll try to **not** disconnect cameras from NVR, but just connect my local network's switch additionally into a free NVRs camera-port: it should be different local IP network in there (will need to route it in my main local network), but I feel this should work...  
This way all cameras should still be working with NVR as usual, providing all ONVIF events and other interactions to this component at the same time...  
I did not try it though, so maybe some Reolink-specific issues could pop up and prevent this...

**Comment by no-compromise** [comment]
Todays update from reolink support:

_Dear Andrej,
 
Thank you for your kind reply.
 
I understand it now. We appreciate your valuable information. In fact, we have reported this problem to our R&D team and our engineer is working hard on this issue.
The solution will probably be out in a month or two. Please kindly wait.
 
Thank you a lot for your understanding and patience.
Looking forward to your reply!_

So, let’s hope that they are working on it as they say. 🙄
